// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: badges.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const awardBadge = `-- name: AwardBadge :one
INSERT INTO user_badges (user_id, badge_id)
VALUES ($1, $2)
ON CONFLICT (user_id, badge_id) DO NOTHING
RETURNING id, user_id, badge_id, earned_at
`

type AwardBadgeParams struct {
	UserID  uuid.UUID `db:"user_id" json:"user_id"`
	BadgeID string    `db:"badge_id" json:"badge_id"`
}

func (q *Queries) AwardBadge(ctx context.Context, arg AwardBadgeParams) (UserBadge, error) {
	row := q.db.QueryRowContext(ctx, awardBadge, arg.UserID, arg.BadgeID)
	var i UserBadge
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BadgeID,
		&i.EarnedAt,
	)
	return i, err
}

const getBadgesByUserIDs = `-- name: GetBadgesByUserIDs :many
SELECT id, user_id, badge_id, earned_at FROM user_badges
WHERE user_id = ANY($1::uuid[])
ORDER BY earned_at
`

func (q *Queries) GetBadgesByUserIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]UserBadge, error) {
	rows, err := q.db.QueryContext(ctx, getBadgesByUserIDs, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserBadge{}
	for rows.Next() {
		var i UserBadge
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.BadgeID,
			&i.EarnedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserBadges = `-- name: GetUserBadges :many
SELECT id, user_id, badge_id, earned_at FROM user_badges
WHERE user_id = $1
ORDER BY earned_at DESC
`

func (q *Queries) GetUserBadges(ctx context.Context, userID uuid.UUID) ([]UserBadge, error) {
	rows, err := q.db.QueryContext(ctx, getUserBadges, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserBadge{}
	for rows.Next() {
		var i UserBadge
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.BadgeID,
			&i.EarnedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hasBadge = `-- name: HasBadge :one
SELECT EXISTS(
    SELECT 1 FROM user_badges
    WHERE user_id = $1 AND badge_id = $2
) AS has_badge
`

type HasBadgeParams struct {
	UserID  uuid.UUID `db:"user_id" json:"user_id"`
	BadgeID string    `db:"badge_id" json:"badge_id"`
}

func (q *Queries) HasBadge(ctx context.Context, arg HasBadgeParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasBadge, arg.UserID, arg.BadgeID)
	var has_badge bool
	err := row.Scan(&has_badge)
	return has_badge, err
}
