// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: holdings.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createHolding = `-- name: CreateHolding :one
INSERT INTO holdings (portfolio_id, symbol, shares, average_cost)
VALUES ($1, $2, $3, $4)
RETURNING id, portfolio_id, symbol, shares, average_cost, created_at, updated_at
`

type CreateHoldingParams struct {
	PortfolioID uuid.UUID `db:"portfolio_id" json:"portfolio_id"`
	Symbol      string    `db:"symbol" json:"symbol"`
	Shares      string    `db:"shares" json:"shares"`
	AverageCost string    `db:"average_cost" json:"average_cost"`
}

func (q *Queries) CreateHolding(ctx context.Context, arg CreateHoldingParams) (Holding, error) {
	row := q.db.QueryRowContext(ctx, createHolding,
		arg.PortfolioID,
		arg.Symbol,
		arg.Shares,
		arg.AverageCost,
	)
	var i Holding
	err := row.Scan(
		&i.ID,
		&i.PortfolioID,
		&i.Symbol,
		&i.Shares,
		&i.AverageCost,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteHolding = `-- name: DeleteHolding :exec
DELETE FROM holdings
WHERE portfolio_id = $1 AND symbol = $2
`

type DeleteHoldingParams struct {
	PortfolioID uuid.UUID `db:"portfolio_id" json:"portfolio_id"`
	Symbol      string    `db:"symbol" json:"symbol"`
}

func (q *Queries) DeleteHolding(ctx context.Context, arg DeleteHoldingParams) error {
	_, err := q.db.ExecContext(ctx, deleteHolding, arg.PortfolioID, arg.Symbol)
	return err
}

const getHoldingBySymbol = `-- name: GetHoldingBySymbol :one
SELECT id, portfolio_id, symbol, shares, average_cost, created_at, updated_at FROM holdings
WHERE portfolio_id = $1 AND symbol = $2
`

type GetHoldingBySymbolParams struct {
	PortfolioID uuid.UUID `db:"portfolio_id" json:"portfolio_id"`
	Symbol      string    `db:"symbol" json:"symbol"`
}

func (q *Queries) GetHoldingBySymbol(ctx context.Context, arg GetHoldingBySymbolParams) (Holding, error) {
	row := q.db.QueryRowContext(ctx, getHoldingBySymbol, arg.PortfolioID, arg.Symbol)
	var i Holding
	err := row.Scan(
		&i.ID,
		&i.PortfolioID,
		&i.Symbol,
		&i.Shares,
		&i.AverageCost,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getHoldingsByPortfolioID = `-- name: GetHoldingsByPortfolioID :many
SELECT id, portfolio_id, symbol, shares, average_cost, created_at, updated_at FROM holdings
WHERE portfolio_id = $1
ORDER BY symbol
`

func (q *Queries) GetHoldingsByPortfolioID(ctx context.Context, portfolioID uuid.UUID) ([]Holding, error) {
	rows, err := q.db.QueryContext(ctx, getHoldingsByPortfolioID, portfolioID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Holding{}
	for rows.Next() {
		var i Holding
		if err := rows.Scan(
			&i.ID,
			&i.PortfolioID,
			&i.Symbol,
			&i.Shares,
			&i.AverageCost,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateHolding = `-- name: UpdateHolding :one
UPDATE holdings
SET shares = $3,
    average_cost = $4,
    updated_at = now()
WHERE portfolio_id = $1 AND symbol = $2
RETURNING id, portfolio_id, symbol, shares, average_cost, created_at, updated_at
`

type UpdateHoldingParams struct {
	PortfolioID uuid.UUID `db:"portfolio_id" json:"portfolio_id"`
	Symbol      string    `db:"symbol" json:"symbol"`
	Shares      string    `db:"shares" json:"shares"`
	AverageCost string    `db:"average_cost" json:"average_cost"`
}

func (q *Queries) UpdateHolding(ctx context.Context, arg UpdateHoldingParams) (Holding, error) {
	row := q.db.QueryRowContext(ctx, updateHolding,
		arg.PortfolioID,
		arg.Symbol,
		arg.Shares,
		arg.AverageCost,
	)
	var i Holding
	err := row.Scan(
		&i.ID,
		&i.PortfolioID,
		&i.Symbol,
		&i.Shares,
		&i.AverageCost,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
