// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Holding struct {
	ID          uuid.UUID    `db:"id" json:"id"`
	PortfolioID uuid.UUID    `db:"portfolio_id" json:"portfolio_id"`
	Symbol      string       `db:"symbol" json:"symbol"`
	Shares      string       `db:"shares" json:"shares"`
	AverageCost string       `db:"average_cost" json:"average_cost"`
	CreatedAt   time.Time    `db:"created_at" json:"created_at"`
	UpdatedAt   sql.NullTime `db:"updated_at" json:"updated_at"`
}

type Portfolio struct {
	ID          uuid.UUID    `db:"id" json:"id"`
	UserID      uuid.UUID    `db:"user_id" json:"user_id"`
	CashBalance string       `db:"cash_balance" json:"cash_balance"`
	CreatedAt   time.Time    `db:"created_at" json:"created_at"`
	UpdatedAt   sql.NullTime `db:"updated_at" json:"updated_at"`
}

type PortfolioSnapshot struct {
	ID           uuid.UUID `db:"id" json:"id"`
	PortfolioID  uuid.UUID `db:"portfolio_id" json:"portfolio_id"`
	TotalValue   string    `db:"total_value" json:"total_value"`
	CashBalance  string    `db:"cash_balance" json:"cash_balance"`
	SnapshotDate time.Time `db:"snapshot_date" json:"snapshot_date"`
	CreatedAt    time.Time `db:"created_at" json:"created_at"`
}

type Transaction struct {
	ID            uuid.UUID `db:"id" json:"id"`
	PortfolioID   uuid.UUID `db:"portfolio_id" json:"portfolio_id"`
	Symbol        string    `db:"symbol" json:"symbol"`
	Type          string    `db:"type" json:"type"`
	Shares        string    `db:"shares" json:"shares"`
	PricePerShare string    `db:"price_per_share" json:"price_per_share"`
	TotalAmount   string    `db:"total_amount" json:"total_amount"`
	CreatedAt     time.Time `db:"created_at" json:"created_at"`
}

type User struct {
	ID           uuid.UUID    `db:"id" json:"id"`
	Email        string       `db:"email" json:"email"`
	PasswordHash string       `db:"password_hash" json:"password_hash"`
	Username     string       `db:"username" json:"username"`
	CreatedAt    time.Time    `db:"created_at" json:"created_at"`
	UpdatedAt    sql.NullTime `db:"updated_at" json:"updated_at"`
}
