// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: portfolios.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createPortfolio = `-- name: CreatePortfolio :one
INSERT INTO portfolios (user_id, cash_balance)
VALUES ($1, $2)
RETURNING id, user_id, cash_balance, created_at, updated_at
`

type CreatePortfolioParams struct {
	UserID      uuid.UUID `db:"user_id" json:"user_id"`
	CashBalance string    `db:"cash_balance" json:"cash_balance"`
}

func (q *Queries) CreatePortfolio(ctx context.Context, arg CreatePortfolioParams) (Portfolio, error) {
	row := q.db.QueryRowContext(ctx, createPortfolio, arg.UserID, arg.CashBalance)
	var i Portfolio
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CashBalance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAllPortfolios = `-- name: GetAllPortfolios :many
SELECT id, user_id, cash_balance, created_at, updated_at FROM portfolios
ORDER BY created_at
`

func (q *Queries) GetAllPortfolios(ctx context.Context) ([]Portfolio, error) {
	rows, err := q.db.QueryContext(ctx, getAllPortfolios)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Portfolio{}
	for rows.Next() {
		var i Portfolio
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CashBalance,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllPortfoliosWithUsers = `-- name: GetAllPortfoliosWithUsers :many
SELECT p.id, p.user_id, p.cash_balance, p.created_at, p.updated_at, u.username
FROM portfolios p
JOIN users u ON u.id = p.user_id
ORDER BY p.created_at
`

type GetAllPortfoliosWithUsersRow struct {
	ID          uuid.UUID    `db:"id" json:"id"`
	UserID      uuid.UUID    `db:"user_id" json:"user_id"`
	CashBalance string       `db:"cash_balance" json:"cash_balance"`
	CreatedAt   time.Time    `db:"created_at" json:"created_at"`
	UpdatedAt   sql.NullTime `db:"updated_at" json:"updated_at"`
	Username    string       `db:"username" json:"username"`
}

func (q *Queries) GetAllPortfoliosWithUsers(ctx context.Context) ([]GetAllPortfoliosWithUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllPortfoliosWithUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllPortfoliosWithUsersRow{}
	for rows.Next() {
		var i GetAllPortfoliosWithUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CashBalance,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPortfolioByID = `-- name: GetPortfolioByID :one
SELECT id, user_id, cash_balance, created_at, updated_at FROM portfolios
WHERE id = $1
`

func (q *Queries) GetPortfolioByID(ctx context.Context, id uuid.UUID) (Portfolio, error) {
	row := q.db.QueryRowContext(ctx, getPortfolioByID, id)
	var i Portfolio
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CashBalance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPortfolioByUserID = `-- name: GetPortfolioByUserID :one
SELECT id, user_id, cash_balance, created_at, updated_at FROM portfolios
WHERE user_id = $1
`

func (q *Queries) GetPortfolioByUserID(ctx context.Context, userID uuid.UUID) (Portfolio, error) {
	row := q.db.QueryRowContext(ctx, getPortfolioByUserID, userID)
	var i Portfolio
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CashBalance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCashBalance = `-- name: UpdateCashBalance :one
UPDATE portfolios
SET cash_balance = $2,
    updated_at   = now()
WHERE id = $1
RETURNING id, user_id, cash_balance, created_at, updated_at
`

type UpdateCashBalanceParams struct {
	ID          uuid.UUID `db:"id" json:"id"`
	CashBalance string    `db:"cash_balance" json:"cash_balance"`
}

func (q *Queries) UpdateCashBalance(ctx context.Context, arg UpdateCashBalanceParams) (Portfolio, error) {
	row := q.db.QueryRowContext(ctx, updateCashBalance, arg.ID, arg.CashBalance)
	var i Portfolio
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CashBalance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
