// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: portfolios.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createPortfolio = `-- name: CreatePortfolio :one
INSERT INTO portfolios (user_id, cash_balance)
VALUES ($1, coalesce($2, 100000.00))
RETURNING id, user_id, cash_balance, created_at, updated_at
`

type CreatePortfolioParams struct {
	UserID  uuid.UUID   `db:"user_id" json:"user_id"`
	Column2 interface{} `db:"column_2" json:"column_2"`
}

func (q *Queries) CreatePortfolio(ctx context.Context, arg CreatePortfolioParams) (Portfolio, error) {
	row := q.db.QueryRowContext(ctx, createPortfolio, arg.UserID, arg.Column2)
	var i Portfolio
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CashBalance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPortfolioByUserID = `-- name: GetPortfolioByUserID :one
SELECT id, user_id, cash_balance, created_at, updated_at FROM portfolios
WHERE user_id = $1
`

func (q *Queries) GetPortfolioByUserID(ctx context.Context, userID uuid.UUID) (Portfolio, error) {
	row := q.db.QueryRowContext(ctx, getPortfolioByUserID, userID)
	var i Portfolio
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CashBalance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCashBalance = `-- name: UpdateCashBalance :one
UPDATE portfolios
SET cash_balance = $2,
    updated_at   = now()
WHERE id = $1
RETURNING id, user_id, cash_balance, created_at, updated_at
`

type UpdateCashBalanceParams struct {
	ID          uuid.UUID `db:"id" json:"id"`
	CashBalance string    `db:"cash_balance" json:"cash_balance"`
}

func (q *Queries) UpdateCashBalance(ctx context.Context, arg UpdateCashBalanceParams) (Portfolio, error) {
	row := q.db.QueryRowContext(ctx, updateCashBalance, arg.ID, arg.CashBalance)
	var i Portfolio
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CashBalance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
