// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: snapshots.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createSnapshot = `-- name: CreateSnapshot :one
INSERT INTO portfolio_snapshots (portfolio_id, total_value, cash_balance, snapshot_date)
VALUES ($1, $2, $3, $4)
ON CONFLICT (portfolio_id, snapshot_date) DO UPDATE
SET total_value = EXCLUDED.total_value,
    cash_balance = EXCLUDED.cash_balance
RETURNING id, portfolio_id, total_value, cash_balance, snapshot_date, created_at
`

type CreateSnapshotParams struct {
	PortfolioID  uuid.UUID `db:"portfolio_id" json:"portfolio_id"`
	TotalValue   string    `db:"total_value" json:"total_value"`
	CashBalance  string    `db:"cash_balance" json:"cash_balance"`
	SnapshotDate time.Time `db:"snapshot_date" json:"snapshot_date"`
}

func (q *Queries) CreateSnapshot(ctx context.Context, arg CreateSnapshotParams) (PortfolioSnapshot, error) {
	row := q.db.QueryRowContext(ctx, createSnapshot,
		arg.PortfolioID,
		arg.TotalValue,
		arg.CashBalance,
		arg.SnapshotDate,
	)
	var i PortfolioSnapshot
	err := row.Scan(
		&i.ID,
		&i.PortfolioID,
		&i.TotalValue,
		&i.CashBalance,
		&i.SnapshotDate,
		&i.CreatedAt,
	)
	return i, err
}

const deleteOldSnapshots = `-- name: DeleteOldSnapshots :exec
DELETE FROM portfolio_snapshots
WHERE snapshot_date < $1
`

func (q *Queries) DeleteOldSnapshots(ctx context.Context, snapshotDate time.Time) error {
	_, err := q.db.ExecContext(ctx, deleteOldSnapshots, snapshotDate)
	return err
}

const getLatestSnapshot = `-- name: GetLatestSnapshot :one
SELECT id, portfolio_id, total_value, cash_balance, snapshot_date, created_at FROM portfolio_snapshots
WHERE portfolio_id = $1
ORDER BY snapshot_date DESC
LIMIT 1
`

func (q *Queries) GetLatestSnapshot(ctx context.Context, portfolioID uuid.UUID) (PortfolioSnapshot, error) {
	row := q.db.QueryRowContext(ctx, getLatestSnapshot, portfolioID)
	var i PortfolioSnapshot
	err := row.Scan(
		&i.ID,
		&i.PortfolioID,
		&i.TotalValue,
		&i.CashBalance,
		&i.SnapshotDate,
		&i.CreatedAt,
	)
	return i, err
}

const getSnapshotsByPortfolioID = `-- name: GetSnapshotsByPortfolioID :many
SELECT id, portfolio_id, total_value, cash_balance, snapshot_date, created_at FROM portfolio_snapshots
WHERE portfolio_id = $1
ORDER BY snapshot_date
`

func (q *Queries) GetSnapshotsByPortfolioID(ctx context.Context, portfolioID uuid.UUID) ([]PortfolioSnapshot, error) {
	rows, err := q.db.QueryContext(ctx, getSnapshotsByPortfolioID, portfolioID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PortfolioSnapshot{}
	for rows.Next() {
		var i PortfolioSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.PortfolioID,
			&i.TotalValue,
			&i.CashBalance,
			&i.SnapshotDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSnapshotsInRange = `-- name: GetSnapshotsInRange :many
SELECT id, portfolio_id, total_value, cash_balance, snapshot_date, created_at FROM portfolio_snapshots
WHERE portfolio_id = $1
  AND snapshot_date BETWEEN $2 AND $3
ORDER BY snapshot_date
`

type GetSnapshotsInRangeParams struct {
	PortfolioID    uuid.UUID `db:"portfolio_id" json:"portfolio_id"`
	SnapshotDate   time.Time `db:"snapshot_date" json:"snapshot_date"`
	SnapshotDate_2 time.Time `db:"snapshot_date_2" json:"snapshot_date_2"`
}

func (q *Queries) GetSnapshotsInRange(ctx context.Context, arg GetSnapshotsInRangeParams) ([]PortfolioSnapshot, error) {
	rows, err := q.db.QueryContext(ctx, getSnapshotsInRange, arg.PortfolioID, arg.SnapshotDate, arg.SnapshotDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PortfolioSnapshot{}
	for rows.Next() {
		var i PortfolioSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.PortfolioID,
			&i.TotalValue,
			&i.CashBalance,
			&i.SnapshotDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
