// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transactions.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (portfolio_id, symbol, type, shares, price_per_share, total_amount)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, portfolio_id, symbol, type, shares, price_per_share, total_amount, created_at
`

type CreateTransactionParams struct {
	PortfolioID   uuid.UUID `db:"portfolio_id" json:"portfolio_id"`
	Symbol        string    `db:"symbol" json:"symbol"`
	Type          string    `db:"type" json:"type"`
	Shares        string    `db:"shares" json:"shares"`
	PricePerShare string    `db:"price_per_share" json:"price_per_share"`
	TotalAmount   string    `db:"total_amount" json:"total_amount"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, createTransaction,
		arg.PortfolioID,
		arg.Symbol,
		arg.Type,
		arg.Shares,
		arg.PricePerShare,
		arg.TotalAmount,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.PortfolioID,
		&i.Symbol,
		&i.Type,
		&i.Shares,
		&i.PricePerShare,
		&i.TotalAmount,
		&i.CreatedAt,
	)
	return i, err
}

const getTransactionsByPortfolioID = `-- name: GetTransactionsByPortfolioID :many
SELECT id, portfolio_id, symbol, type, shares, price_per_share, total_amount, created_at
FROM transactions
WHERE portfolio_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetTransactionsByPortfolioIDParams struct {
	PortfolioID uuid.UUID `db:"portfolio_id" json:"portfolio_id"`
	Limit       int32     `db:"limit" json:"limit"`
	Offset      int32     `db:"offset" json:"offset"`
}

func (q *Queries) GetTransactionsByPortfolioID(ctx context.Context, arg GetTransactionsByPortfolioIDParams) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, getTransactionsByPortfolioID, arg.PortfolioID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.PortfolioID,
			&i.Symbol,
			&i.Type,
			&i.Shares,
			&i.PricePerShare,
			&i.TotalAmount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionsBySymbol = `-- name: GetTransactionsBySymbol :many
SELECT id, portfolio_id, symbol, type, shares, price_per_share, total_amount, created_at
FROM transactions
WHERE portfolio_id = $1 AND symbol = $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type GetTransactionsBySymbolParams struct {
	PortfolioID uuid.UUID `db:"portfolio_id" json:"portfolio_id"`
	Symbol      string    `db:"symbol" json:"symbol"`
	Limit       int32     `db:"limit" json:"limit"`
	Offset      int32     `db:"offset" json:"offset"`
}

func (q *Queries) GetTransactionsBySymbol(ctx context.Context, arg GetTransactionsBySymbolParams) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, getTransactionsBySymbol,
		arg.PortfolioID,
		arg.Symbol,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.PortfolioID,
			&i.Symbol,
			&i.Type,
			&i.Shares,
			&i.PricePerShare,
			&i.TotalAmount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
