// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: watchlist.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addWatchlistItem = `-- name: AddWatchlistItem :one
INSERT INTO watchlist_items (user_id, symbol)
VALUES ($1, $2)
RETURNING id, user_id, symbol, added_at
`

type AddWatchlistItemParams struct {
	UserID uuid.UUID `db:"user_id" json:"user_id"`
	Symbol string    `db:"symbol" json:"symbol"`
}

func (q *Queries) AddWatchlistItem(ctx context.Context, arg AddWatchlistItemParams) (WatchlistItem, error) {
	row := q.db.QueryRowContext(ctx, addWatchlistItem, arg.UserID, arg.Symbol)
	var i WatchlistItem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Symbol,
		&i.AddedAt,
	)
	return i, err
}

const countWatchlistItems = `-- name: CountWatchlistItems :one
SELECT COUNT(*) FROM watchlist_items
WHERE user_id = $1
`

func (q *Queries) CountWatchlistItems(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countWatchlistItems, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getWatchlistByUserID = `-- name: GetWatchlistByUserID :many
SELECT id, user_id, symbol, added_at FROM watchlist_items
WHERE user_id = $1
ORDER BY added_at DESC
`

func (q *Queries) GetWatchlistByUserID(ctx context.Context, userID uuid.UUID) ([]WatchlistItem, error) {
	rows, err := q.db.QueryContext(ctx, getWatchlistByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WatchlistItem{}
	for rows.Next() {
		var i WatchlistItem
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Symbol,
			&i.AddedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWatchlistItem = `-- name: GetWatchlistItem :one
SELECT id, user_id, symbol, added_at FROM watchlist_items
WHERE user_id = $1 AND symbol = $2
`

type GetWatchlistItemParams struct {
	UserID uuid.UUID `db:"user_id" json:"user_id"`
	Symbol string    `db:"symbol" json:"symbol"`
}

func (q *Queries) GetWatchlistItem(ctx context.Context, arg GetWatchlistItemParams) (WatchlistItem, error) {
	row := q.db.QueryRowContext(ctx, getWatchlistItem, arg.UserID, arg.Symbol)
	var i WatchlistItem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Symbol,
		&i.AddedAt,
	)
	return i, err
}

const removeWatchlistItem = `-- name: RemoveWatchlistItem :exec
DELETE FROM watchlist_items
WHERE user_id = $1 AND symbol = $2
`

type RemoveWatchlistItemParams struct {
	UserID uuid.UUID `db:"user_id" json:"user_id"`
	Symbol string    `db:"symbol" json:"symbol"`
}

func (q *Queries) RemoveWatchlistItem(ctx context.Context, arg RemoveWatchlistItemParams) error {
	_, err := q.db.ExecContext(ctx, removeWatchlistItem, arg.UserID, arg.Symbol)
	return err
}
